### ISSUE TITLE
Markdown to PDF: non-english characters are lost.

### ISSUE THREAD

**Issue by jdhao** [hackmdio/codimd#945] opened 2018-09-07 04:59 UTC
I am trying to use the service provided on <https://hackmd-ce.herokuapp.com/> to write Markdown. All Chinese characters are lost in the PDF generated by the download  pdf link. My example Markdown is <https://hackmd-ce.herokuapp.com/xUkpXMZ-Tv-47_u_QcP0pA?both>.

**Comment by jackycute** [comment] 2018-09-07 06:10
Hi @jdhao 
The instance generate PDF will need install fonts of the languages that content have or it will just be broken blocks.
And the Chinese fonts actually have very big file size and usually need to be installed manually.

**Comment by jdhao** [comment] 2018-09-07 06:49
So is there a solution right now?  I have heard that there are some web-optimized font to minimize storage overhead.

**Comment by BinotaLIU** [comment] 2018-09-07 08:08
@jdhao Since PDF file is generated on the server side, you need to install fonts **on the server**. For Chinese, you can consider to install the package `wqy-micro-hei`(or `wqy-microhei`), which is available on most package managers.

**Comment by ccoenen** [comment] 2018-09-07 11:31
we should add this as an optional step to the setup instructions. Is anyone interested in making a proposal?

**Comment by bonanza123** [comment] 2018-10-14 12:13
Not sure if it fits this issue, but the PDF does not contain rendered math such as `$ x= a$`. Instead, it shows just the plain text.
Also, the PDF does have bookmarks for every section, as the HTML does.

**Comment by u23a** [comment] 2018-12-25 07:14
Hope adding the Chinese support to official docker image.

**Comment by jdhao** [comment] 2019-01-25 03:18
Some open source font which support a wide range of unicode character would be preferable, e.g., [Source han sans](https://github.com/adobe-fonts/source-han-sans), which is well designed and comprehensive.

**Comment by SISheogorath** [comment] 2019-01-25 09:11
@jdhaoi was looking for them yesterday, since I came to the idea to look into this issue when they were updated on my Fedora setup. But somehow I couldn't find the corresponding Debian package .-. which means either I'm not good at finding debian packages or there is none. But since those fonts are recommended I might just install them manually.

**Comment by SISheogorath** [comment] 2019-01-25 17:34
At least for container-based setups this should be fixed as soon as this is merged:

https://github.com/hackmdio/codimd-container/pull/19

**Comment by jgrocha** [comment] 2020-03-08 23:21
I not sure if this issue is the right place, but I have all non English characters included in the PDF.

My problem is related to the noto font. The font does not render properly even with English text only. 

I have, for example, this document: https://md.geomaster.pt/s/5pLxArsiO#

The document looks nice on the browser, but when I export it, it uses the noto font, which makes the document less readable. The PDF I get it is: [Corona%20Virus%20visualization%20in%20QGIS.pdf](https://github.com/hackmdio/codimd/files/4304013/Corona.20Virus.20visualization.20in.20QGIS.pdf)

The code blocks, for example, are well rendered in the PDF.

Is there a way to select which fonts should be used in the PDF?

**Comment by jgrocha** [comment] 2020-03-10 23:25
As a work around, I'm downloading the document and then run `markdown-pdf`on the command line, with `markdown-pdf` default options. This way, the Noto fonts are not used and the output is much more readable.

I've tried to look at the code https://github.com/hackmdio/codimd/blob/e33bafd35dc441b265598cc073d3459fc06b80a0/lib/note/noteActions.js#L67

There is no reference to a custom css, so I don't really know why and where the Noto fonts are being used.

**Comment by jackycute** [comment] 2021-05-12 15:51
Hi @jdhao,

You can now use docker image with CJK fonts inside and the export PDF should render characters properly.
https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-docker-deployment#Pick-docker-image-for-CJK-fonts

Feel free to reopen if you can reproduce this in the latest version, thank you!

**Closed by jackycute** 2021-05-12 15:51 UTC
Labels: bug
