### ISSUE TITLE
Way to disable keyboard shortcuts

### ISSUE THREAD

**Issue by younishd** [hackmdio/codimd#530] opened 2017-08-20 15:12 UTC
It would be nice to have a feature to disable the keyboard shortcuts.

**Comment by younishd** [comment] 2017-10-06 22:52
`Ctrl+T` seems to flip the two characters that are on the left and right of the cursor, but it also opens a new tab in most browsers.

The last time I checked (e.g., when I opened this issue) it kept doing both at the same time if I accidentally pressed it while in edit mode, which was very annoying so I stopped doing that and used the mouse to open a new tab instead while editing.
I just retested it now and it seems like browser shortcuts are now correctly overridden as it no longer opens a new tab when I press `Ctrl+T` (although the "Allow override browser keymap" option has no effect on that).

It would be great to have a way of disabling a shortcut like `Ctrl+T` so that the browser would just open a new tab.

**Comment by SISheogorath** [comment] 2017-10-09 22:13
Mhm, I just tested myself and can't reproduce it. Chromium as well as Firefox seem to open a new tab but not swap any characters.

What browser are you using? And what version of HackMD? Self-hosted? HackMD.io?

**Comment by ccoenen** [comment] 2018-06-26 20:07
I'm closing this for now, as it hasn't gotten any feedback, and the issue itself seems to be gone. Feel free to reopen at any time if this still bothers you!

**Closed by ccoenen** 2018-06-26 20:07 UTC
Labels: Hacktoberfest, bug
